In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)

comparing 

In [7]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/Users/nandan/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9777777777777777

In [8]:
svc = SVC()
svc.fit(X_train,y_train)
svc.score(X_test,y_test)

0.9888888888888889

In [9]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train,y_train)
randomForest.score(X_test,y_test)

0.9861111111111112

the problem with test_train_split is that
the model will get biased towards that particular split of data set(u can change the data set split then the op of score of model also changes)

so u divide the model into batches and u give different batches to test it 
and there by reducing the bias involved

In [12]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [13]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


In [24]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [25]:
from sklearn.model_selection import StratifiedKFold
# StratifiedKFold divides the data set uniformly

folds=StratifiedKFold(n_splits=4)

In [32]:
scores_log=[]
scores_svm=[]
scores_randFor=[]

for train_index , test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    
    scores_log.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_randFor.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

/Users/nandan/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/nandan/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#log

In [33]:
scores_log

[0.9355555555555556,
 0.9153674832962138,
 0.9510022271714922,
 0.9175946547884187]

In [34]:
scores_svm

[0.9644444444444444,
 0.9665924276169265,
 0.9821826280623608,
 0.9487750556792873]

In [35]:
scores_randFor

[0.94, 0.9198218262806236, 0.9688195991091314, 0.9175946547884187]

no need to write this much of score also 

In [38]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target)

/Users/nandan/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/nandan/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#log

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [39]:
cross_val_score(SVC(),digits.data,digits.target)


array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [40]:
cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target)


array([0.93055556, 0.88888889, 0.95264624, 0.96100279, 0.90250696])

In [41]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)


array([0.91388889, 0.89444444, 0.95264624, 0.97214485, 0.91364903])